### ISSUE TITLE
Please update dependencies !

### ISSUE THREAD

**Issue by RoarGronmo** [andyhorn/flutter_resizable_container#1]
Thank you for a handy widget !

I see there are som outdated dependencies, could you please try to upgrade them?

![image](https://github.com/andyhorn/flutter_resizable_container/assets/11217296/05a7a0c4-c020-4c51-9ddc-48051e4dc225)

**Comment by andyhorn** [comment]
Dependencies have been updated as of 0.2.0. Thank you!
