### ISSUE TITLE
Unhandled exception during hot reboot.

### ISSUE THREAD

**Issue by ivanmem** [andyhorn/flutter_resizable_container#22]
![image](https://github.com/andyhorn/flutter_resizable_container/assets/33786293/23fe1f58-7081-4b0f-b821-0d01dcdbca47)
![image](https://github.com/andyhorn/flutter_resizable_container/assets/33786293/bd796648-04eb-4d18-867b-9afbccd0d9d7)

```dart
════════ Exception caught by widgets library ═══════════════════════════════════
The following RangeError was thrown building Builder(dirty):
RangeError (index): Invalid value: Valid value range is empty: 0

The relevant error-causing widget was:
    ResizableContainer ResizableContainer:file:///F:/Projects/flutter/sql_inspect/lib/src/app.dart:1091:24

When the exception was thrown, this was the stack:
#0      List.[] (dart:core-patch/growable_array.dart:264:36)
growable_array.dart:264
#1      _ResizableContainerState._getChildSize (package:flutter_resizable_container/src/resizable_container.dart:204:16)
resizable_container.dart:204
#2      _ResizableContainerState.build.<anonymous closure>.<anonymous closure> (package:flutter_resizable_container/src/resizable_container.dart:130:34)
resizable_container.dart:130
#3      Builder.build (package:flutter/src/widgets/basic.dart:7682:48)
basic.dart:7682
#4      StatelessElement.build (package:flutter/src/widgets/framework.dart:5541:49)
framework.dart:5541
#5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5471:15)
framework.dart:5471
#6      Element.rebuild (package:flutter/src/widgets/framework.dart:5187:7)
framework.dart:5187
#7      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2895:19)
framework.dart:2895
#8      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:984:21)
binding.dart:984

```
Can anything be done about this? Interferes with debugging.

**Comment by andyhorn** [comment]
Hi @ivanmem, I'll take a look into this 👍 

What target (iOS, Android, Web, etc) is this occurring on?
Is this happening every-time you hot-restart or is it intermittent?

**Comment by ivanmem** [comment]
> Hi @ivanmem, I'll take a look into this 👍
> 
> What target (iOS, Android, Web, etc) is this occurring on? Is this happening every-time you hot-restart or is it intermittent?
1) windows
2) every

**Comment by andyhorn** [comment]
@ivanmem can you provide any sample code that reproduces this? I tried the example app on web, mac, and Windows, but I'm not seeing this error.

**Comment by ivanmem** [comment]
https://github.com/ivanmem/flutter_resizable_container_exception
![image](https://github.com/andyhorn/flutter_resizable_container/assets/33786293/b2285a0e-27d9-48d0-8a37-61f4348a5c4d)

**Comment by andyhorn** [comment]
Thank you, I can reproduce - I'm not sure why it wasn't happening with the example, but I see the cause of the error now and will begin working on a fix 👍

**Comment by andyhorn** [comment]
For context: The error is occurring because a hot-reload is triggering the `didUpdateWidget` lifecycle hook. In this hook, we are reinitializing the controller, but then the check (`oldWidget.direction != widget.direction)` is failing and not re-populating the new controller.

I have been trying to make efforts to improve the controller feature, but this can/should be solved immediately.
