### ISSUE TITLE
[question] Is it normal to recreate a controller for each build?

### ISSUE THREAD

**Issue by ivanmem** [andyhorn/flutter_resizable_container#30]
I have some widgets that should not be displayed in full screen mode of the application, so I have to recreate the controller on each build. Is it normal to do this and will this behavior be supported in the future?

![image](https://github.com/andyhorn/flutter_resizable_container/assets/33786293/1be1b35d-aa12-4fc3-9c9f-ddb24d3ea15f)

**Comment by andyhorn** [comment]
I hadn't thought of this use-case; I'll look into a better solution!

**Comment by andyhorn** [comment]
Hi @ivanmem, I am releasing a beta version that addresses your concern by moving the `ResizableChild` items back into the `ResizableController`. Are you interested in testing things out before I make a full release?

**Comment by ivanmem** [comment]
@andyhorn thanks, that's what I need. Only the controller seems like it should be optional, as its functionality is not always needed.
