### ISSUE TITLE
Option to define startingSize on ResizableChild

### ISSUE THREAD

**Issue by jonathanfristedt** [andyhorn/flutter_resizable_container#37]
Hello!

Thanks for making this package, Im building a side panel view with it.

Would it be possible to add the option of defining a startingSize on ResizableChild that can be used instead of a starting ratio? It would be great if the other ResizableChild could be set to expand to take up all available space if no ratio is used. I would've submitted a PR but just learning to code hehe.

**Comment by andyhorn** [comment]
I like this idea - I have something in the works and will try to include it in a v1 release (coming soon)

**Comment by jonathanfristedt** [comment]
Nice!! Looking forward to use it.

I'd like to add then that in my case I'd like to be able to set starting size as a pixel value on two out of 3 resizables. As I also will have a right panel later on. So left and right: pixel value, middle: expands.

**Comment by andyhorn** [comment]
I have this feature published as a pre-release on `pub.dev`. Check out version 2.0.0-beta.2

**Comment by jonathanfristedt** [comment]
Just gave it a go! Nice. Is it possible to make the ResizableChild stick to its size while resizing the window as well? I'd like for it to stay in the defined size or the size a user sets it to, whilst changing overall window size.

**Comment by andyhorn** [comment]
If I understand you correctly, instead of scaling the children uniformly as the window size increases, only scale the "expanding" middle section (with the null `startingSize`)?

**Comment by jonathanfristedt** [comment]
Yes Exactly!

**Comment by jonathanfristedt** [comment]
A bonus / nice to have would be that the widget remembers the previous size of the !hidden ResizableChild when unhiding it.

**Comment by andyhorn** [comment]
I'm nearing completion on your "expand" idea and I think it works really nicely.

As for the "remember previous size," I think this would be something you could accomplish by using the controller in your own program. You could extract the current sizes, hide the widget, then display the widget and set the sizes back - or something along those lines. 

I don't think it's something that needs to be supported internally.

**Comment by jonathanfristedt** [comment]
Sweeeet! You're quick. I'm looking forward to give it a spin. :)

Yea fair enough, I can make it work that way 👍

**Comment by andyhorn** [comment]
Ok, check out beta.3 (https://pub.dev/packages/flutter_resizable_container/versions/2.0.0-beta.3).

I think I like this setup and will likely make a full release soon. Thanks for all your input!

**Comment by jonathanfristedt** [comment]
Nice work. It works perfectly! Thanks for being receptive!
