### ISSUE TITLE
Feature request: Option to make a smaller fixed-size divider

### ISSUE THREAD

**Issue by brainwo** [andyhorn/flutter_resizable_container#45]
In addition to [indent](https://pub.dev/documentation/flutter_resizable_container/latest/flutter_resizable_container/ResizableDivider/indent.html) and [endIndent](https://pub.dev/documentation/flutter_resizable_container/latest/flutter_resizable_container/ResizableDivider/endIndent.html), I would like to request a cross axis size. This will allow a divider to be visually in a fixed size, just like how a divider looks like in other frameworks.

For reference this is how a resizable diver/handlebar looks in Qt/Krita:
![image](https://github.com/user-attachments/assets/6113428b-1890-4bf6-80d5-28984da6cfe1)

Using indent and endIndent would be too hacky since it requires the divider to be recalculated on resize.

**Comment by andyhorn** [comment]
Hi @brainwo,

I've taken your feedback, along with feedback from others and some ideas I've been mulling over, and am working on an update that changes how you configure the `ResizableDivider`. One of these changes is to set a `length` for the divider that uses the `ResizableSize` class - this will allow you to specify a fixed length (e.g. 25px) or a ratio (e.g. 10%).

See #49

**Comment by brainwo** [comment]
This is also works perfectly as intended. Thank you again!
