### ISSUE TITLE
Larger size but borders should still connect

### ISSUE THREAD

**Issue by dominictobias** [andyhorn/flutter_resizable_container#48]
Hi, is there a way to set the size to e.g. `10` so that the resize bars are easy to grip, but have the borders still be connected? I think this would be the desired behaviour in most cases anyway.

i.e. these should be connected:

```dart
final divider = ResizableDivider(
  color: hovered ? Colors.blue : outline,
  thickness: 1,
  size: 10,
  onHoverEnter: () => setState(() => hovered = true),
  onHoverExit: () => setState(() => hovered = false),
);
```

<img width="137" alt="Screenshot 2024-08-15 at 8 19 06 PM" src="https://github.com/user-attachments/assets/fa333188-65b8-41e4-a7d2-fd13fab833c4">

**Comment by andyhorn** [comment]
Hi @dominictobias,

I think the `thickness` property will give you the result you're looking for.

In addition, I'm working on some updates to the `ResizableDivider` to make it more flexible and (hopefully) easier to use. See my PR #49

**Comment by andyhorn** [comment]
@dominictobias can you verify if this is still an issue?

**Comment by dominictobias** [comment]
Hey sorry @andyhorn no longer working on this so feel free to close it. Thanks for your response, I've forgotten if I tried it or not now 😅
