### ISSUE TITLE
Active divider color on mouse hover

### ISSUE THREAD

**Issue by dldjseh** [andyhorn/flutter_resizable_container#50]
Hello!

Thanks for making this package, I'm building a side panel view with it.

Is it possible to change the color of only the active divider on mouse hover in ResizableDivider?
Currently, if there are more than 2 dividers, the colors of all dividers are updated.

**Comment by andyhorn** [comment]
Oh, that's definitely a bug! I'll take a look at it soon 👍🏻

**Comment by andyhorn** [comment]
Just now getting back to this, my apologies. 

Unfortunately, I think this is a limitation/defect in the design. I set it up with a single divider configuration that applies to _all_ dividers within the container. I'll have to look into a way to customize each divider without making it too verbose and clunky. 🤔

**Comment by mikeryder** [comment]
Would you take a PR on this?  Looking at it, I think we can do the following:
- Accept a new parameter to the ResizableContainerDivider for colorOverride that supersedes the color in the config
- ResizableContainer takes a new parameter for List<Color> dividerColors that, if it provided, needs to have a length one less than the length of children
- In ResizableContainer @163, if dividerColors is not empty and dividerColors[i] != null, pass dividerColors[i] in for the colorOverride 

Let me know what you think.  (I am running into the same issue)

**Comment by Levi-Lesches** [comment]
@mikeryder, what about instead: 
- add `Color color` to `ResizableContainerDivider`
- add a new parameter, `List<ResizableContainerDivider>? allDividers`  to `ResizableContainer`
  - as you said, length must be n - 1, where n = children.length
- throw an ArgumentError if `allDividers` and `divider` are both not null, as one is a fallback for the other

This way, every property of the dividers can be fully customized, not just the color

**Comment by andyhorn** [comment]
@Levi-Lesches I think you're on the right path. 

If we were in TypeScript, I could just make the `divider` property accept a single item or a list, but maybe I can use a sealed class to do the same here in Dart. It would be a breaking change, but what do you both think about something like:

```dart
sealed class ResizableDividerConfig {
  const ResizableDividerConfig();
}

final class SingleDivider extends ResizableDividerConfig {
  const SingleDivider(this.divider);

  final ResizableDivider divider;
}

final class DividerList extends ResizableDividerConfig {
  const DividerList(this.dividers);

  final List<ResizableDivider> dividers;
}
```

Then, you could use:

```dart
ResizableContainer(
  divider: SingleDivider(ResizableDivider(...)),
),
```

or

```dart
ResizableContainer(
  divider: DividerList([
    ResizableDivider(...),
    ResizableDivider(...),
  ]),
),
```

It adds a little verbosity but would make it more flexible. Then, to both your points, if we're using the list, it would have to have a length of n-1.

**Comment by mikeryder** [comment]
In my initial suggestion, I minimized changes and kept it non-breaking. If you're going with a breaking change, I would just make the divider param be a list (consistent with children always being a list). Maybe a better way to go that might feel more consistent with other Flutter container widgets is to support the ResizableDivider as a child in the children list of ResizableContainer. This would be non-breaking as the existing divider parameter would be essentially the default divider and the child Dividers would supersede the default.

**Comment by andyhorn** [comment]
I've started working on an experiment that places the divider config inside the `ResizableChild` (checkout the `resizable_child_divider` branch).

I'm already planning on releasing a v4 with some other breaking changes, so it would make sense to make these changes at the same time.

**Comment by mikeryder** [comment]
This sounds great. Do you have a sense of the timeline for v4 release?

**Comment by andyhorn** [comment]
I'm really trying to get a non-beta released by the end of the year. I was hoping to have it completed by Christmas, which _might_ still happen. But EOY seems a safe bet.

**Comment by andyhorn** [comment]
I just published beta.4 (https://pub.dev/packages/flutter_resizable_container/versions/4.0.0-beta.4)

I think this is pretty much ready to release but I want to take one more quick pass 👍

**Comment by mikeryder** [comment]
Great! I'll add it to my project as beta.

**Comment by andyhorn** [comment]
v4 officially released this morning!
