### ISSUE TITLE
Precision issue when setting ratios manually

### ISSUE THREAD

**Issue by Levi-Lesches** [andyhorn/flutter_resizable_container#54]
Here's are the ratios I am setting, on a controller with 2 children: 
```dart
[0.8362927091740651, 0.16370729082593485]
```
Adding them yields: `0.9999999999999999`, but I still get the following error: 
```console
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument(s): The sum of the ratios must equal 1
#0      ResizableController.setRatios (package:flutter_resizable_container/src/resizable_controller.dart:32:7)
resizable_controller.dart:32
#1      ViewsModel.loadPreset (package:rover_dashboard/src/models/data/views.dart:84:62)
views.dart:84
<asynchronous suspension>
```

Adding a small epsilon value should help.

**Comment by Levi-Lesches** [comment]
Ah, just realizing that I'm still on `0.4.2`. Upgrading to `3.0.0` fixed it.

**Comment by andyhorn** [comment]
> Ah, just realizing that I'm still on `0.4.2`. Upgrading to `3.0.0` fixed it.

Glad to hear that it's not still an issue!
