### ISSUE TITLE
The minSize,maxSize constraint is invalid when the window size changes

### ISSUE THREAD

**Issue by rongyu-zhen** [andyhorn/flutter_resizable_container#59]
Hello!
Thanks a lot for this package, I'm using it to build my desktop apps.

Currently, when changing the window size, the minSize and maxSize constraints are invalid!
![PixPin_2024-11-17_21-57-02](https://github.com/user-attachments/assets/cb930c56-58f1-49d2-872b-4d0c8fea9dc8)

**Comment by andyhorn** [comment]
Good catch! 👍 

I think we're currently adjusting the sizes uniformly when changing the window size, but it should definitely respect any min/max size constraints.

**Comment by andyhorn** [comment]
This issue was partially fixed by #60 (#58), but there is still an overflow is some scenarios because the dividers aren't being accounted for.

**Comment by andyhorn** [comment]
This will be resolved in #65

**Comment by andyhorn** [comment]
A pre-release version (4.0.0-beta.1) is available on pub.dev that includes a full fix for this issue.

**Comment by andyhorn** [comment]
This issue has been fixed and will be included in the next release, coming very soon!
