### ISSUE TITLE
When resizing a child past its minimum size, another child gets resized

### ISSUE THREAD

**Issue by kekland** [andyhorn/flutter_resizable_container#6]
Hi!

Thanks for this amazing package! Saved me from having to implement this from scratch :)

Just noticed a small issue that happens when you specify a `minSize` for children. It happens when you try to resize the child past its minimum size. For some reason a different child becomes bigger when that happens.

See the attached video:

https://github.com/andyhorn/flutter_resizable_container/assets/14993994/a3c7160c-651f-4ad0-92c5-938e50653e89

Here's the code to reproduce this:

```dart
    return ResizableContainer(
      direction: Axis.horizontal,
      dividerWidth: 1.0,
      dividerColor: Theme.of(context).dividerColor.withOpacity(0.4),
      children: [
        ResizableChildData(
          startingRatio: 0.25,
          minSize: 100.0,
          child: SizedBox.expand(),
        ),
        ResizableChildData(
          startingRatio: 0.25,
          minSize: 100.0,
          child: SizedBox.expand(),
        ),
        ResizableChildData(
          startingRatio: 0.5,
          minSize: 200.0,
          child: SizedBox.expand(),
        ),
      ],
    );
```

**Comment by Levi-Lesches** [comment]
I guess you can think of it as "the left child is too small to shrink more, but the middle child is requesting more space, so the right child compromises". Maybe that's a good thing?

**Comment by andyhorn** [comment]
Oh, wow. That's interesting.

Thanks for reporting! It definitely shouldn't resize in the opposite direction haha. I'll dig into it!
