### ISSUE TITLE
Update package at pub.dev to 3.0.1

### ISSUE THREAD

**Issue by rbkantor** [andyhorn/flutter_resizable_container#64]
Hi,

would it be possible to update the package at pub.dev to 3.0.1 as the fix for issue #58 was merged into the main branch.

Thanks

**Comment by andyhorn** [comment]
Yes, I was hoping to make a release with other improvements, but they're taking longer than anticipated. 

I will get this patch released ASAP.

**Comment by andyhorn** [comment]
https://pub.dev/packages/flutter_resizable_container/versions/3.0.1
