### ISSUE TITLE
bug: Ratio sizes should track during screen resizing

### ISSUE THREAD

**Issue by andyhorn** [andyhorn/flutter_resizable_container#66]
**Expected:**

When resizing the screen, any children with a "ratio" size should maintain their ratio.

**Actual:**

When resizing the screen, the change is distributed amongst "expand" children first, if available, and then equally amongst all non-shrink children.

**Caveats:**

This might not be possible/feasible, since there is no way of knowing if a ratio child has been resized. If we then try to enforce the ratio during a screen resize, it could cause unwanted behavior (resizing the child "back" to its ratio).

More thought/discussion is necessary to determine if this is a desired behavior.

**Comment by Levi-Lesches** [comment]
> This might not be possible/feasible, since there is no way of knowing if a ratio child has been resized.

I wonder if this is worth investigating, separately. I don't think I have a need for it though.

**Comment by andyhorn** [comment]
I've changed my mind and don't think this is particularly useful; closing.
