### ISSUE TITLE
When TextDirection.rtl resizing is the opposite of the dragging direction

### ISSUE THREAD

**Issue by dorklein** [andyhorn/flutter_resizable_container#69]
It works with:
```dart
Directionality(
      textDirection: TextDirection.ltr,
...
```

It fails with:
```dart
Directionality(
      textDirection: TextDirection.rtl,
...
```

**Comment by andyhorn** [comment]
I'm working on a new v4 release at the moment, and will make sure to include this in that release, but I will also try to get this included as a patch in v3 first.
